FROM --platform=linux/amd64 python:3.13-slim

WORKDIR /app
COPY requirements.txt /app/
RUN python3.13 -m pip install --upgrade pip && python3.13 -m pip install -r requirements.txt

COPY . /app

EXPOSE 8001
CMD ["python3.13", "-m", "src.main"]